# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/harrisabdullah/Documents/vscode_projs/c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/harrisabdullah/Documents/vscode_projs/c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/harrisabdullah/Documents/vscode_projs/c/CMakeFiles /Users/harrisabdullah/Documents/vscode_projs/c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/harrisabdullah/Documents/vscode_projs/c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named psudo_interprator_2

# Build rule for target.
psudo_interprator_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 psudo_interprator_2
.PHONY : psudo_interprator_2

# fast build rule for target.
psudo_interprator_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/build
.PHONY : psudo_interprator_2/fast

ExecutionEngine/ExecutionEngine.o: ExecutionEngine/ExecutionEngine.c.o
.PHONY : ExecutionEngine/ExecutionEngine.o

# target to build an object file
ExecutionEngine/ExecutionEngine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/ExecutionEngine.c.o
.PHONY : ExecutionEngine/ExecutionEngine.c.o

ExecutionEngine/ExecutionEngine.i: ExecutionEngine/ExecutionEngine.c.i
.PHONY : ExecutionEngine/ExecutionEngine.i

# target to preprocess a source file
ExecutionEngine/ExecutionEngine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/ExecutionEngine.c.i
.PHONY : ExecutionEngine/ExecutionEngine.c.i

ExecutionEngine/ExecutionEngine.s: ExecutionEngine/ExecutionEngine.c.s
.PHONY : ExecutionEngine/ExecutionEngine.s

# target to generate assembly for a file
ExecutionEngine/ExecutionEngine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/ExecutionEngine.c.s
.PHONY : ExecutionEngine/ExecutionEngine.c.s

ExecutionEngine/Namespace.o: ExecutionEngine/Namespace.c.o
.PHONY : ExecutionEngine/Namespace.o

# target to build an object file
ExecutionEngine/Namespace.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/Namespace.c.o
.PHONY : ExecutionEngine/Namespace.c.o

ExecutionEngine/Namespace.i: ExecutionEngine/Namespace.c.i
.PHONY : ExecutionEngine/Namespace.i

# target to preprocess a source file
ExecutionEngine/Namespace.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/Namespace.c.i
.PHONY : ExecutionEngine/Namespace.c.i

ExecutionEngine/Namespace.s: ExecutionEngine/Namespace.c.s
.PHONY : ExecutionEngine/Namespace.s

# target to generate assembly for a file
ExecutionEngine/Namespace.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/Namespace.c.s
.PHONY : ExecutionEngine/Namespace.c.s

ExecutionEngine/Resolver.o: ExecutionEngine/Resolver.c.o
.PHONY : ExecutionEngine/Resolver.o

# target to build an object file
ExecutionEngine/Resolver.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/Resolver.c.o
.PHONY : ExecutionEngine/Resolver.c.o

ExecutionEngine/Resolver.i: ExecutionEngine/Resolver.c.i
.PHONY : ExecutionEngine/Resolver.i

# target to preprocess a source file
ExecutionEngine/Resolver.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/Resolver.c.i
.PHONY : ExecutionEngine/Resolver.c.i

ExecutionEngine/Resolver.s: ExecutionEngine/Resolver.c.s
.PHONY : ExecutionEngine/Resolver.s

# target to generate assembly for a file
ExecutionEngine/Resolver.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/Resolver.c.s
.PHONY : ExecutionEngine/Resolver.c.s

ExecutionEngine/resolveIdentifier.o: ExecutionEngine/resolveIdentifier.c.o
.PHONY : ExecutionEngine/resolveIdentifier.o

# target to build an object file
ExecutionEngine/resolveIdentifier.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/resolveIdentifier.c.o
.PHONY : ExecutionEngine/resolveIdentifier.c.o

ExecutionEngine/resolveIdentifier.i: ExecutionEngine/resolveIdentifier.c.i
.PHONY : ExecutionEngine/resolveIdentifier.i

# target to preprocess a source file
ExecutionEngine/resolveIdentifier.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/resolveIdentifier.c.i
.PHONY : ExecutionEngine/resolveIdentifier.c.i

ExecutionEngine/resolveIdentifier.s: ExecutionEngine/resolveIdentifier.c.s
.PHONY : ExecutionEngine/resolveIdentifier.s

# target to generate assembly for a file
ExecutionEngine/resolveIdentifier.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/ExecutionEngine/resolveIdentifier.c.s
.PHONY : ExecutionEngine/resolveIdentifier.c.s

Parser/Parser.o: Parser/Parser.c.o
.PHONY : Parser/Parser.o

# target to build an object file
Parser/Parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/Parser.c.o
.PHONY : Parser/Parser.c.o

Parser/Parser.i: Parser/Parser.c.i
.PHONY : Parser/Parser.i

# target to preprocess a source file
Parser/Parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/Parser.c.i
.PHONY : Parser/Parser.c.i

Parser/Parser.s: Parser/Parser.c.s
.PHONY : Parser/Parser.s

# target to generate assembly for a file
Parser/Parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/Parser.c.s
.PHONY : Parser/Parser.c.s

Parser/parseAssignment.o: Parser/parseAssignment.c.o
.PHONY : Parser/parseAssignment.o

# target to build an object file
Parser/parseAssignment.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseAssignment.c.o
.PHONY : Parser/parseAssignment.c.o

Parser/parseAssignment.i: Parser/parseAssignment.c.i
.PHONY : Parser/parseAssignment.i

# target to preprocess a source file
Parser/parseAssignment.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseAssignment.c.i
.PHONY : Parser/parseAssignment.c.i

Parser/parseAssignment.s: Parser/parseAssignment.c.s
.PHONY : Parser/parseAssignment.s

# target to generate assembly for a file
Parser/parseAssignment.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseAssignment.c.s
.PHONY : Parser/parseAssignment.c.s

Parser/parseDeclare.o: Parser/parseDeclare.c.o
.PHONY : Parser/parseDeclare.o

# target to build an object file
Parser/parseDeclare.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseDeclare.c.o
.PHONY : Parser/parseDeclare.c.o

Parser/parseDeclare.i: Parser/parseDeclare.c.i
.PHONY : Parser/parseDeclare.i

# target to preprocess a source file
Parser/parseDeclare.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseDeclare.c.i
.PHONY : Parser/parseDeclare.c.i

Parser/parseDeclare.s: Parser/parseDeclare.c.s
.PHONY : Parser/parseDeclare.s

# target to generate assembly for a file
Parser/parseDeclare.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseDeclare.c.s
.PHONY : Parser/parseDeclare.c.s

Parser/parseElse.o: Parser/parseElse.c.o
.PHONY : Parser/parseElse.o

# target to build an object file
Parser/parseElse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseElse.c.o
.PHONY : Parser/parseElse.c.o

Parser/parseElse.i: Parser/parseElse.c.i
.PHONY : Parser/parseElse.i

# target to preprocess a source file
Parser/parseElse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseElse.c.i
.PHONY : Parser/parseElse.c.i

Parser/parseElse.s: Parser/parseElse.c.s
.PHONY : Parser/parseElse.s

# target to generate assembly for a file
Parser/parseElse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseElse.c.s
.PHONY : Parser/parseElse.c.s

Parser/parseExpression.o: Parser/parseExpression.c.o
.PHONY : Parser/parseExpression.o

# target to build an object file
Parser/parseExpression.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseExpression.c.o
.PHONY : Parser/parseExpression.c.o

Parser/parseExpression.i: Parser/parseExpression.c.i
.PHONY : Parser/parseExpression.i

# target to preprocess a source file
Parser/parseExpression.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseExpression.c.i
.PHONY : Parser/parseExpression.c.i

Parser/parseExpression.s: Parser/parseExpression.c.s
.PHONY : Parser/parseExpression.s

# target to generate assembly for a file
Parser/parseExpression.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseExpression.c.s
.PHONY : Parser/parseExpression.c.s

Parser/parseFor.o: Parser/parseFor.c.o
.PHONY : Parser/parseFor.o

# target to build an object file
Parser/parseFor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseFor.c.o
.PHONY : Parser/parseFor.c.o

Parser/parseFor.i: Parser/parseFor.c.i
.PHONY : Parser/parseFor.i

# target to preprocess a source file
Parser/parseFor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseFor.c.i
.PHONY : Parser/parseFor.c.i

Parser/parseFor.s: Parser/parseFor.c.s
.PHONY : Parser/parseFor.s

# target to generate assembly for a file
Parser/parseFor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseFor.c.s
.PHONY : Parser/parseFor.c.s

Parser/parseIf.o: Parser/parseIf.c.o
.PHONY : Parser/parseIf.o

# target to build an object file
Parser/parseIf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseIf.c.o
.PHONY : Parser/parseIf.c.o

Parser/parseIf.i: Parser/parseIf.c.i
.PHONY : Parser/parseIf.i

# target to preprocess a source file
Parser/parseIf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseIf.c.i
.PHONY : Parser/parseIf.c.i

Parser/parseIf.s: Parser/parseIf.c.s
.PHONY : Parser/parseIf.s

# target to generate assembly for a file
Parser/parseIf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseIf.c.s
.PHONY : Parser/parseIf.c.s

Parser/parseOutput.o: Parser/parseOutput.c.o
.PHONY : Parser/parseOutput.o

# target to build an object file
Parser/parseOutput.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseOutput.c.o
.PHONY : Parser/parseOutput.c.o

Parser/parseOutput.i: Parser/parseOutput.c.i
.PHONY : Parser/parseOutput.i

# target to preprocess a source file
Parser/parseOutput.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseOutput.c.i
.PHONY : Parser/parseOutput.c.i

Parser/parseOutput.s: Parser/parseOutput.c.s
.PHONY : Parser/parseOutput.s

# target to generate assembly for a file
Parser/parseOutput.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseOutput.c.s
.PHONY : Parser/parseOutput.c.s

Parser/parseRepeat.o: Parser/parseRepeat.c.o
.PHONY : Parser/parseRepeat.o

# target to build an object file
Parser/parseRepeat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseRepeat.c.o
.PHONY : Parser/parseRepeat.c.o

Parser/parseRepeat.i: Parser/parseRepeat.c.i
.PHONY : Parser/parseRepeat.i

# target to preprocess a source file
Parser/parseRepeat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseRepeat.c.i
.PHONY : Parser/parseRepeat.c.i

Parser/parseRepeat.s: Parser/parseRepeat.c.s
.PHONY : Parser/parseRepeat.s

# target to generate assembly for a file
Parser/parseRepeat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseRepeat.c.s
.PHONY : Parser/parseRepeat.c.s

Parser/parseWhile.o: Parser/parseWhile.c.o
.PHONY : Parser/parseWhile.o

# target to build an object file
Parser/parseWhile.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseWhile.c.o
.PHONY : Parser/parseWhile.c.o

Parser/parseWhile.i: Parser/parseWhile.c.i
.PHONY : Parser/parseWhile.i

# target to preprocess a source file
Parser/parseWhile.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseWhile.c.i
.PHONY : Parser/parseWhile.c.i

Parser/parseWhile.s: Parser/parseWhile.c.s
.PHONY : Parser/parseWhile.s

# target to generate assembly for a file
Parser/parseWhile.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Parser/parseWhile.c.s
.PHONY : Parser/parseWhile.c.s

Tokenisation/Tokenizer.o: Tokenisation/Tokenizer.c.o
.PHONY : Tokenisation/Tokenizer.o

# target to build an object file
Tokenisation/Tokenizer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Tokenisation/Tokenizer.c.o
.PHONY : Tokenisation/Tokenizer.c.o

Tokenisation/Tokenizer.i: Tokenisation/Tokenizer.c.i
.PHONY : Tokenisation/Tokenizer.i

# target to preprocess a source file
Tokenisation/Tokenizer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Tokenisation/Tokenizer.c.i
.PHONY : Tokenisation/Tokenizer.c.i

Tokenisation/Tokenizer.s: Tokenisation/Tokenizer.c.s
.PHONY : Tokenisation/Tokenizer.s

# target to generate assembly for a file
Tokenisation/Tokenizer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/Tokenisation/Tokenizer.c.s
.PHONY : Tokenisation/Tokenizer.c.s

common/List.o: common/List.c.o
.PHONY : common/List.o

# target to build an object file
common/List.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/common/List.c.o
.PHONY : common/List.c.o

common/List.i: common/List.c.i
.PHONY : common/List.i

# target to preprocess a source file
common/List.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/common/List.c.i
.PHONY : common/List.c.i

common/List.s: common/List.c.s
.PHONY : common/List.s

# target to generate assembly for a file
common/List.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/common/List.c.s
.PHONY : common/List.c.s

common/Stack.o: common/Stack.c.o
.PHONY : common/Stack.o

# target to build an object file
common/Stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/common/Stack.c.o
.PHONY : common/Stack.c.o

common/Stack.i: common/Stack.c.i
.PHONY : common/Stack.i

# target to preprocess a source file
common/Stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/common/Stack.c.i
.PHONY : common/Stack.c.i

common/Stack.s: common/Stack.c.s
.PHONY : common/Stack.s

# target to generate assembly for a file
common/Stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/common/Stack.c.s
.PHONY : common/Stack.c.s

common/tokenTypeToString.o: common/tokenTypeToString.c.o
.PHONY : common/tokenTypeToString.o

# target to build an object file
common/tokenTypeToString.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/common/tokenTypeToString.c.o
.PHONY : common/tokenTypeToString.c.o

common/tokenTypeToString.i: common/tokenTypeToString.c.i
.PHONY : common/tokenTypeToString.i

# target to preprocess a source file
common/tokenTypeToString.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/common/tokenTypeToString.c.i
.PHONY : common/tokenTypeToString.c.i

common/tokenTypeToString.s: common/tokenTypeToString.c.s
.PHONY : common/tokenTypeToString.s

# target to generate assembly for a file
common/tokenTypeToString.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/common/tokenTypeToString.c.s
.PHONY : common/tokenTypeToString.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psudo_interprator_2.dir/build.make CMakeFiles/psudo_interprator_2.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... psudo_interprator_2"
	@echo "... ExecutionEngine/ExecutionEngine.o"
	@echo "... ExecutionEngine/ExecutionEngine.i"
	@echo "... ExecutionEngine/ExecutionEngine.s"
	@echo "... ExecutionEngine/Namespace.o"
	@echo "... ExecutionEngine/Namespace.i"
	@echo "... ExecutionEngine/Namespace.s"
	@echo "... ExecutionEngine/Resolver.o"
	@echo "... ExecutionEngine/Resolver.i"
	@echo "... ExecutionEngine/Resolver.s"
	@echo "... ExecutionEngine/resolveIdentifier.o"
	@echo "... ExecutionEngine/resolveIdentifier.i"
	@echo "... ExecutionEngine/resolveIdentifier.s"
	@echo "... Parser/Parser.o"
	@echo "... Parser/Parser.i"
	@echo "... Parser/Parser.s"
	@echo "... Parser/parseAssignment.o"
	@echo "... Parser/parseAssignment.i"
	@echo "... Parser/parseAssignment.s"
	@echo "... Parser/parseDeclare.o"
	@echo "... Parser/parseDeclare.i"
	@echo "... Parser/parseDeclare.s"
	@echo "... Parser/parseElse.o"
	@echo "... Parser/parseElse.i"
	@echo "... Parser/parseElse.s"
	@echo "... Parser/parseExpression.o"
	@echo "... Parser/parseExpression.i"
	@echo "... Parser/parseExpression.s"
	@echo "... Parser/parseFor.o"
	@echo "... Parser/parseFor.i"
	@echo "... Parser/parseFor.s"
	@echo "... Parser/parseIf.o"
	@echo "... Parser/parseIf.i"
	@echo "... Parser/parseIf.s"
	@echo "... Parser/parseOutput.o"
	@echo "... Parser/parseOutput.i"
	@echo "... Parser/parseOutput.s"
	@echo "... Parser/parseRepeat.o"
	@echo "... Parser/parseRepeat.i"
	@echo "... Parser/parseRepeat.s"
	@echo "... Parser/parseWhile.o"
	@echo "... Parser/parseWhile.i"
	@echo "... Parser/parseWhile.s"
	@echo "... Tokenisation/Tokenizer.o"
	@echo "... Tokenisation/Tokenizer.i"
	@echo "... Tokenisation/Tokenizer.s"
	@echo "... common/List.o"
	@echo "... common/List.i"
	@echo "... common/List.s"
	@echo "... common/Stack.o"
	@echo "... common/Stack.i"
	@echo "... common/Stack.s"
	@echo "... common/tokenTypeToString.o"
	@echo "... common/tokenTypeToString.i"
	@echo "... common/tokenTypeToString.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

