//
// Created by Harris on 03/09/2024.
//

#ifndef PSUDO_INTERPRATOR_2_INTERNAL_ERRORS_H
#define PSUDO_INTERPRATOR_2_INTERNAL_ERRORS_H

void ie_allocationError();

#endif // PSUDO_INTERPRATOR_2_INTERNAL_ERRORS_H